### PR TITLE
remove mentoring.mozilla.com aws resources

### PR DESCRIPTION
**Pull request by cmharlow**
Jira ticket: https://jira.mozilla.com/browse/SE-1978

What this PR does:
* removes AWS resources for mentoring.mozilla.com

Why do this now:
* already decomming other mentoring stuff for the cluster migration work

Next steps after PR approval:
1. ~run terraform apply, removing all mentoring resources~
2. ~check infoblox for any lingering DNS related to mentoring~
3. ~archive this git repository (or ask someone with sufficient git permissions to archive it)~
4. ~remove the terraform state bucket related to this project~

Note: I comment out the resources instead of straight out delete the file in case its ever helpful in terms of searching archived repos in the future. Also can just delete the terraform files if preferred.

### CODE REVIEW

**Review by sciurus — APPROVED** [review]
If you can't archive, let me know and I'll switch to my owner account and do it.

Could you share the `terraform plan` output before executing it, so we get a second pair of eyes to ensure it won't have any unintended effects?

**Comment by cmharlow** [comment]
> If you can't archive, let me know and I'll switch to my owner account and do it.
> 
> Could you share the `terraform plan` output before executing it, so we get a second pair of eyes to ensure it won't have any unintended effects?

sure @sciurus 

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # aws_acm_certificate.mentoring_mozilla_com will be destroyed
  - resource "aws_acm_certificate" "mentoring_mozilla_com" {
      - arn                       = "arn:aws:acm:us-west-2:783633885093:certificate/5f9c551f-66bb-4bcb-a985-994931785c3d" -> null
      - domain_name               = "mentoring.mozilla.com" -> null
      - domain_validation_options = [
          - {
              - domain_name           = "mentoring.mozilla.com"
              - resource_record_name  = "_498ab006568efb1023bb831dac5432ec.mentoring.mozilla.com."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_4ab8a4f1bd61870a62a7d95e86524ffd.hkmpvcwbzw.acm-validations.aws."
            },
        ] -> null
      - id                        = "arn:aws:acm:us-west-2:783633885093:certificate/5f9c551f-66bb-4bcb-a985-994931785c3d" -> null
      - status                    = "ISSUED" -> null
      - subject_alternative_names = [] -> null
      - tags                      = {} -> null
      - tags_all                  = {} -> null
      - validation_emails         = [] -> null
      - validation_method         = "DNS" -> null

      - options {
          - certificate_transparency_logging_preference = "ENABLED" -> null
        }
    }

  # aws_acm_certificate_validation.mentoring_mozilla_com will be destroyed
  - resource "aws_acm_certificate_validation" "mentoring_mozilla_com" {
      - certificate_arn         = "arn:aws:acm:us-west-2:783633885093:certificate/5f9c551f-66bb-4bcb-a985-994931785c3d" -> null
      - id                      = "2021-02-23 09:48:01 +0000 UTC" -> null
      - validation_record_fqdns = [
          - "_498ab006568efb1023bb831dac5432ec.mentoring.mozilla.com",
        ] -> null
    }

  # aws_route53_record.mentoring_mozilla_com["mentoring.mozilla.com"] will be destroyed
  - resource "aws_route53_record" "mentoring_mozilla_com" {
      - allow_overwrite = true -> null
      - fqdn            = "_498ab006568efb1023bb831dac5432ec.mentoring.mozilla.com" -> null
      - id              = "Z0519832EFKB1SRHTLRQ__498ab006568efb1023bb831dac5432ec.mentoring.mozilla.com._CNAME" -> null
      - name            = "_498ab006568efb1023bb831dac5432ec.mentoring.mozilla.com" -> null
      - records         = [
          - "_4ab8a4f1bd61870a62a7d95e86524ffd.hkmpvcwbzw.acm-validations.aws.",
        ] -> null
      - ttl             = 60 -> null
      - type            = "CNAME" -> null
      - zone_id         = "{taken out}" -> null
    }

  # aws_route53_zone.primary will be destroyed
  - resource "aws_route53_zone" "primary" {
      - comment       = "Managed by Terraform" -> null
      - force_destroy = false -> null
      - id            = "{taken out}" -> null
      - name          = "mentoring.mozilla.com" -> null
      - name_servers  = [
          - "ns-1110.awsdns-10.org",
          - "ns-1624.awsdns-11.co.uk",
          - "ns-92.awsdns-11.com",
          - "ns-977.awsdns-58.net",
        ] -> null
      - tags          = {} -> null
      - tags_all      = {} -> null
      - zone_id       = "{taken out}" -> null
    }

  # module.database-prod.aws_db_instance.default will be destroyed
  - resource "aws_db_instance" "default" {
      - address                               = "mentoring-prod.{taken out}.us-west-2.rds.amazonaws.com" -> null
      - allocated_storage                     = 5 -> null
      - allow_major_version_upgrade           = false -> null
      - apply_immediately                     = false -> null
      - arn                                   = "arn:aws:rds:us-west-2:783633885093:db:mentoring-prod" -> null
      - auto_minor_version_upgrade            = true -> null
      - availability_zone                     = "us-west-2a" -> null
      - backup_retention_period               = 30 -> null
      - backup_window                         = "07:41-08:11" -> null
      - ca_cert_identifier                    = "rds-ca-2019" -> null
      - copy_tags_to_snapshot                 = false -> null
      - db_subnet_group_name                  = "mentoring-prod-subnet_group" -> null
      - delete_automated_backups              = true -> null
      - deletion_protection                   = false -> null
      - enabled_cloudwatch_logs_exports       = [] -> null
      - endpoint                              = "mentoring-prod.{taken out}.us-west-2.rds.amazonaws.com:5432" -> null
      - engine                                = "postgres" -> null
      - engine_version                        = "12.5" -> null
      - hosted_zone_id                        = "{taken out}" -> null
      - iam_database_authentication_enabled   = false -> null
      - id                                    = "mentoring-prod" -> null
      - identifier                            = "mentoring-prod" -> null
      - instance_class                        = "db.t3.micro" -> null
      - iops                                  = 0 -> null
      - latest_restorable_time                = "2021-06-10T17:36:58Z" -> null
      - license_model                         = "postgresql-license" -> null
      - maintenance_window                    = "thu:11:25-thu:11:55" -> null
      - max_allocated_storage                 = 0 -> null
      - monitoring_interval                   = 0 -> null
      - multi_az                              = false -> null
      - name                                  = "mentoring" -> null
      - option_group_name                     = "default:postgres-12" -> null
      - parameter_group_name                  = "default.postgres12" -> null
      - password                              = (sensitive value)
      - performance_insights_enabled          = false -> null
      - performance_insights_retention_period = 0 -> null
      - port                                  = 5432 -> null
      - publicly_accessible                   = false -> null
      - replicas                              = [] -> null
      - resource_id                           = "db-{taken out}" -> null
      - security_group_names                  = [] -> null
      - skip_final_snapshot                   = true -> null
      - status                                = "storage-full" -> null
      - storage_encrypted                     = false -> null
      - storage_type                          = "gp2" -> null
      - tags                                  = {
          - "CostCenter"  = "1410"
          - "Environment" = "prod"
          - "Name"        = "mentoring"
          - "Project"     = "mentoring"
          - "Region"      = "us-west-2"
          - "Terraform"   = "true"
        } -> null
      - tags_all                              = {
          - "CostCenter"  = "1410"
          - "Environment" = "prod"
          - "Name"        = "mentoring"
          - "Project"     = "mentoring"
          - "Region"      = "us-west-2"
          - "Terraform"   = "true"
        } -> null
      - username                              = "mentoring" -> null
      - vpc_security_group_ids                = [
          - "sg-{taken out}",
        ] -> null
    }

  # module.database-prod.aws_db_subnet_group.subnet will be destroyed
  - resource "aws_db_subnet_group" "subnet" {
      - arn         = "arn:aws:rds:us-west-2:783633885093:subgrp:mentoring-prod-subnet_group" -> null
      - description = "Managed by Terraform" -> null
      - id          = "mentoring-prod-subnet_group" -> null
      - name        = "mentoring-prod-subnet_group" -> null
      - subnet_ids  = [
          - "subnet-{taken out}",
          - "subnet-{taken out}",
          - "subnet-{taken out}",
        ] -> null
      - tags        = {} -> null
      - tags_all    = {} -> null
    }

  # module.database-prod.aws_security_group.default will be destroyed
  - resource "aws_security_group" "default" {
      - arn                    = "arn:aws:ec2:us-west-2:783633885093:security-group/sg-{taken out}" -> null
      - description            = "Managed by Terraform" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-{taken out}" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "172.16.0.0/16",
                ]
              - description      = "postgres"
              - from_port        = 5432
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 5432
            },
        ] -> null
      - name                   = "mentoring-prod-security_group" -> null
      - owner_id               = "783633885093" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "CostCenter"  = "1410"
          - "Environment" = "prod"
          - "Name"        = "mentoring-prod-rds-sg"
          - "Project"     = "mentoring"
          - "Region"      = "us-west-2"
          - "Terraform"   = "true"
        } -> null
      - tags_all               = {
          - "CostCenter"  = "1410"
          - "Environment" = "prod"
          - "Name"        = "mentoring-prod-rds-sg"
          - "Project"     = "mentoring"
          - "Region"      = "us-west-2"
          - "Terraform"   = "true"
        } -> null
      - vpc_id                 = "vpc-{taken out}" -> null
    }

  # module.database-prod.random_password.password will be destroyed
  - resource "random_password" "password" {
      - id          = "none" -> null
      {taken out}
    }

  # module.ecr.aws_ecr_repository.this will be destroyed
  - resource "aws_ecr_repository" "this" {
      - arn                  = "arn:aws:ecr:us-west-2:783633885093:repository/mentoring" -> null
      - id                   = "mentoring" -> null
      - image_tag_mutability = "MUTABLE" -> null
      - name                 = "mentoring" -> null
      - registry_id          = "783633885093" -> null
      - repository_url       = "783633885093.dkr.ecr.us-west-2.amazonaws.com/mentoring" -> null
      - tags                 = {
          - "Name"      = "mentoring"
          - "Region"    = "us-west-2"
          - "Terraform" = "true"
        } -> null
      - tags_all             = {
          - "Name"      = "mentoring"
          - "Region"    = "us-west-2"
          - "Terraform" = "true"
        } -> null

      - encryption_configuration {
          - encryption_type = "AES256" -> null
        }

      - image_scanning_configuration {
          - scan_on_push = true -> null
        }
    }

  # module.ecr.aws_iam_access_key.this[0] will be destroyed
  - resource "aws_iam_access_key" "this" {
      - create_date          = "2021-02-15T11:30:53Z" -> null
      - id                   = "{taken out}" -> null
      - secret               = (sensitive value)
      - ses_smtp_password_v4 = (sensitive value)
      - status               = "Active" -> null
      - user                 = "ecr-mentoring-iam" -> null
    }

  # module.ecr.aws_iam_user.this[0] will be destroyed
  - resource "aws_iam_user" "this" {
      - arn           = "arn:aws:iam::783633885093:user/ecr-mentoring-iam" -> null
      - force_destroy = false -> null
      - id            = "ecr-mentoring-iam" -> null
      - name          = "ecr-mentoring-iam" -> null
      - path          = "/" -> null
      - tags          = {
          - "Name"      = "ecr-mentoring-iam"
          - "Terraform" = "true"
        } -> null
      - tags_all      = {
          - "Name"      = "ecr-mentoring-iam"
          - "Terraform" = "true"
        } -> null
      - unique_id     = "{taken out}" -> null
    }

  # module.ecr.aws_iam_user_policy.this[0] will be destroyed
  - resource "aws_iam_user_policy" "this" {
      - id     = "ecr-mentoring-iam:ecr-mentoring-access" -> null
      - name   = "ecr-mentoring-access" -> null
      - policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "ecr:GetAuthorizationToken"
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = "GetAuthorizationToken"
                    },
                  - {
                      - Action   = [
                          - "ecr:UploadLayerPart",
                          - "ecr:PutImage",
                          - "ecr:InitiateLayerUpload",
                          - "ecr:GetDownloadUrlForLayer",
                          - "ecr:CompleteLayerUpload",
                          - "ecr:BatchGetImage",
                          - "ecr:BatchCheckLayerAvailability",
                        ]
                      - Effect   = "Allow"
                      - Resource = "arn:aws:ecr:us-west-2:783633885093:repository/mentoring"
                      - Sid      = "AllowPush"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
      - user   = "ecr-mentoring-iam" -> null
    }

Plan: 0 to add, 0 to change, 12 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

**Comment by duallain** [comment]
Plan LGTM.  All resources have mentoring in the name, so it seems unlikely to have unintended consequences.

Because we're removing a subdomain from r53 (mentoring.mozilla.com), we should be nice to rtucker and remove the infoblox side. @cmharlow  I can do that after you apply the change, just let me know.

**Comment by cmharlow** [comment]
Alright, resources removed. Proceeding with merge and rest of steps in PR description.

**Pull request merged**
